language: java

jdk:
  - oraclejdk8

install:
  - ./gradlew assemble -x signArchives -x uploadArchives

script:
  - ./gradlew check --debug --stacktrace --info

after_success:
  - ./gradlew jacocoTestReport coveralls
